name: Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get changelog
        run: curl -LJO https://raw.githubusercontent.com/nkilders/carta-nautica/main/changelogs/${{ env.RELEASE_VERSION }}.md

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install

      - name: Copy Web Assets
        run: ionic capacitor copy

      - name: Build Android App
        run: ionic capacitor build android --no-open

      - name: Generate APK
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv ./android/app/build/outputs/apk/debug/app-debug.apk ./carta-nautica-${{ env.RELEASE_VERSION }}.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ env.RELEASE_VERSION }}.md
          files: ./carta-nautica-${{ env.RELEASE_VERSION }}.apk
